### ISSUE TITLE
Excuse me, have you reproduced the results of the paper?

### ISSUE THREAD

**Issue by liguge** [hectorLop/Conditional-Adversarial-Domain-Generalization-with-Single-Discriminator#1]

**Comment by hectorLop** [comment]
Hi, not actually. I have only used this implementation for a project in my job. Therefore, this implementation may lead to different results than those obtained in the original paper.

Sorry if there are some errors, and this led you to confusion.

**Comment by liguge** [comment]
OK, I see. thanks very much.❤️
